### ISSUE TITLE
[FEATURE]: Before and after execution support for ModalCommandsModule

### ISSUE THREAD

**Issue by deniz-blue** [XeroxDev/DSharpPlus.ModuleCommands#1]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.

### Feature

title is self explanatory. see ButtonCommands or SlashCommands libs

### Solution

implement it lmao

**Comment by XeroxDev** [comment]
Sorry for the late reply. 

AFAIK button commands don't support this as well (I know this mainly because I used the code from it for this extension).

Could you send me more examples / the locations where these features are implemented in those libraries? Then I'll add them as soon as I've time.

**Comment by TheAlan404** [comment]
https://gitlab.com/kuylar/DSharpPlus.ButtonCommands/-/commit/2068673a1f0da0ee1d666d04309905053119cd59

**Comment by XeroxDev** [comment]
Thank you.

I'll add it soon as well.

/label -details +accepted +progress
