### ISSUE TITLE
[QUESTION]: <Dispose Implementation Error>

### ISSUE THREAD

**Issue by MontoyaTM** [XeroxDev/DSharpPlus.ModuleCommands#7]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.

### Question

Hey, 

While trying to start my program, I continue to get an error about a dispose method not having an implementation. I did not see any related issue so I am wondering if I am doing something wrong.

`System.TypeLoadException: 'Method 'Dispose' in type 'DSharpPlus.ModalCommands.ModalCommandsExtension' from assembly 'XeroxDev.DSharpPlus.ModalCommands, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'`

**Comment by MontoyaTM** [comment]
I am using the DSharpPlus 4.42 version

**Comment by XeroxDev** [comment]
Hey. Sorry for the late response. v4.4+ is currently not supported due to major changes. In the next update, I'll change the packages from nightly to stable 4.4+, then it should work.
